name: Filter Issue
description: Report filter problems, request new filters, or report broken site functionality.
body:
  - type: markdown
    attributes:
      value: |
        **Quick checklist before submitting:**
        - ✅ Only uBlock Origin enabled
        - ✅ Filter lists updated (🛡️ icon > 🔄 button)
        - ✅ Tested in incognito/private mode
        - ✅ No duplicate issue exists
        
        <details>
        <summary>💡 Common Solutions (click to expand)</summary>
        
        **Before reporting, try these:**
        1. **Clear browser cache** - Sometimes old cached content causes issues
        2. **Disable cosmetic filtering** - Click uBO icon > 👁️ eye icon to test
        3. **Check if it's a regional issue** - Some ads only appear in specific countries
        4. **Try a hard refresh** - Press `Ctrl+F5` (Windows) or `Cmd+Shift+R` (Mac)
        5. **Check the element with inspect** - Right-click element > Inspect to see its class/id
        
        </details>
        
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I searched for similar issues and found none
          required: true
        - label: I tested with ONLY uBlock Origin enabled
          required: true
        - label: I updated all filter lists (🔄 button)
          required: true
        - label: I tested in incognito/private mode
          required: true
        - label: I did NOT complete all the above steps
          required: false
          
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      options:
        - "🚫 Element not blocked (ad, popup, banner, etc.)"
        - "💔 Filter breaks site functionality"
        - "🔧 Improvement to existing filter"
        - "✨ New filter request"
        - "🐛 Other"
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🌐 URL(s)
      description: Where does the issue occur? (At least one URL required)
      placeholder: |
        https://example.com/page-with-issue
        https://subdomain.example.com/another-page
        
        Note: Mark as NSFW if applicable
      render: yaml
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📝 Description
      description: Be specific - this helps us fix the issue faster
      placeholder: |
        What's wrong:
        A floating video ad appears in the bottom-right corner after 5 seconds on every page.
        
        What should happen:
        The ad should be blocked without breaking the video player or page layout.
        
        When it started:
        Started appearing around October 15, 2025.
        
        Element details (if you inspected it):
        <div class="sticky-ad-container" id="bottom-ad">
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🖥️ System Information
      description: Browser and uBlock Origin versions
      placeholder: |
        Browser: Firefox 120.0 / Chrome 119.0.6045.199 / Edge 119.0.2151.72
        uBlock Origin: 1.54.0
        OS: Windows 11 / macOS Sonoma / Ubuntu 22.04 (optional)
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📸 Screenshots
      description: |
        **Required** - Visual proof helps tremendously
        💡 Include: the issue + uBO panel showing active filters
        🔴 NSFW content: post links, not inline images
      value: |
        <details>
        <summary>Screenshots</summary>

        <!-- Drag and drop images here -->
        <!-- Show: 1) The problematic element, 2) uBO panel if possible -->


        </details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔧 Troubleshooting Information
      description: |
        **How to get it:** Page with issue > 🛡️ uBO icon > 💬 Report > Scroll down > "Troubleshooting Information"
      value: |
        <details>
        <summary>Troubleshooting Information</summary>

        ```yaml
        # Paste troubleshooting info here
        
        
        ```
        </details>
    validations:
      required: false

  - type: textarea
    attributes:
      label: ℹ️ Additional Context
      description: Anything else that might help
      placeholder: |
        Examples:
        - Only happens when logged in
        - Only appears in Spain/Mexico/etc.
        - Started after site redesign
        - Other extensions installed: Privacy Badger, Dark Reader
        - Tried filter: example.com##.ad-container (didn't work)
    validations:
      required: false