name: Filter Issue
description: Report issues with existing filters, request new filters, or report sites not working properly.
body:
  - type: markdown
    attributes:
      value: |
        To avoid burdening **MAINTAINERS** with invalid or duplicate reports, disregarding these steps **WILL** result in your issue being closed immediately.
        
        > [!IMPORTANT]
        > #### Before reporting, verify:
        > - The issue persists with **only uBlock Origin enabled**
        > - You have updated all filter lists (🛡️ uBO icon > 🔄 Update button)
        > - There is no similar issue already reported
        
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        **IMPORTANT:** Answer carefully and truthfully.
      options:
        - label: I have read the [repository documentation](https://github.com/Suurp/uBlock-CustomFilters/blob/main/README.md) and understand the purpose of these filters.
          required: true
        - label: I have verified that this issue is not a duplicate using the [issue search](https://github.com/Suurp/uBlock-CustomFilters/issues).
          required: true
        - label: I have tested with **only uBlock Origin enabled** (all other extensions disabled).
          required: true
        - label: I have updated all filter lists by clicking the 🔄 update button in uBlock Origin's dashboard.
          required: true
        - label: I have verified that the issue persists in **incognito/private mode**.
          required: true
        - label: I have verified that I have the **latest version** of uBlock Origin installed.
          required: true
        - label: If reporting a filter breaking a site, I have verified that the issue disappears when disabling filters from this repository.
          required: true
        - label: I have updated my browser to the latest available version.
          required: true
        - label: I did NOT answer truthfully to **ALL** the above checkboxes.
          required: false
          
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: Select the type of issue you are reporting
      options:
        - "🚫 Element not blocked (ad, popup, banner)"
        - "💔 Filter breaks site functionality"
        - "🔧 Improvement to existing filter"
        - "✨ New filter request"
        - "🐛 Other issue"
    validations:
      required: true

  - type: textarea
    attributes:
      label: URL(s) where the issue occurs
      description: |
        At least one URL is **MANDATORY** for issues affecting web pages.
        Mark with **"NSFW"** where applicable.
      placeholder: |
        https://example.com
        https://example.org/page
        https://example.net/specific
      render: yaml
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description of the Issue
      description: |
        Provide a clear and concise description of the issue.
        - What is happening?
        - What should happen?
        - When did the issue start?
      placeholder: |
        Example: The floating banner at the bottom of example.com is not blocked by current filters.
        It should be completely blocked without affecting the page content.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Relevant Filter (if applicable)
      description: |
        If the issue is with a specific existing filter in this repository, paste it here.
        Indicate the file and line number if possible.
      placeholder: |
        File: filters.txt, line 123
        Filter: example.com##.floating-ad
      render: text
    validations:
      required: false

  - type: textarea
    attributes:
      label: Browser Name and Version
      description: Provide the exact name and version of your browser.
      placeholder: |
        Example: 
        - Firefox 120.0
        - Chrome 119.0.6045.199
        - Edge 119.0.2151.72
    validations:
      required: true

  - type: textarea
    attributes:
      label: uBlock Origin Version
      description: |
        Find the version at: uBO icon > ⚙️ > "About" tab
      placeholder: |
        Example: 1.54.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other Extensions Installed
      description: |
        List other extensions you have installed (write _none_ if there are no others).
        This information helps investigate potential conflicts.
      placeholder: |
        - Privacy Badger
        - Dark Reader
        - none
    validations:
      required: true

  - type: textarea
    attributes:
      label: Country/Region
      description: | 
        Not required, but some sites or issues are only accessible or reproducible from specific countries.
        If you think your issue is of this type, indicate which country you are accessing from.
      placeholder: |
        Example: United States, Spain, Mexico, etc.
        Or write: _Not relevant_
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots
      description: |
        Screenshots are **MANDATORY**.
        🔴 Post **LINKS** instead of inline images for screenshots containing **ADULT MATERIAL**. 🔴
        
        💡 Tip: Include screenshots showing:
        - The problematic element (with developer console open if possible)
        - The uBlock Origin panel showing active filters
      value: |
        <details>
        <summary>Screenshots</summary>

        <!-- Drag-and-drop screenshots here -->
        <!-- ⬇️  ⬇️  ⬇️ -->


        <!-- ⬆️  ⬆️  ⬆️ -->

        </details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Troubleshooting Information
      description: |
        On the page where the issue occurs:
        1. 🛡️ Click on the uBlock Origin icon
        2. 💬 Click on the "Report" button (chat icon)
        3. Scroll to the bottom
        4. Click on "Troubleshooting Information"
        5. Copy and paste the information here
        
        If you cannot obtain this information, at least indicate:
        - Active filter lists in uBlock Origin
        - Whether you have additional custom filters
      value: |
        <details>
        <summary>Configuration Details</summary>

        <!-- ⬇️ Paste troubleshooting information here ⬇️ -->
        ```yaml


        ```
        </details>    
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Any other details that may be useful:
        - Does the issue only occur on certain devices?
        - Is there any temporal pattern? (only certain days/times)
        - Have you tried any temporary solutions?
      placeholder: |
        The issue only occurs after logging into the site.
        I tried adding the filter example.com##.new-banner but it doesn't work.
    validations:
      required: false